### ISSUE TITLE
bug when switching from 'info' to 'action' in an equipment

### ISSUE THREAD

**Issue by diving91** [jeedom/core#123]
Hi,
When switching from 'Info' to 'Action' in an equipment, a new  drop down list is presented with the possible actions on that equipment.
Without saving the equipment, when going back to 'Info', the drop down list is still present whereas it should disappear.

The same is also true for a dialog box in the Options. This dialog box is called "Valeur de l'info", It also should be removed when switching to 'info' type

**Comment by zoic21** [comment]
Thank, it's fix in last beta of jeedom
