### ISSUE TITLE
LDAP connect

### ISSUE THREAD

**Issue by zougoulou59** [jeedom/core#130]
Hello,
I have a brand new jeedom installation,

I'n trying to get LDAP working.

I got this :
```×500 : Internal Server Error```

and in the logs nginx.error :
```2015/06/10 19:40:08 [error] 1451#0: *4462 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function ldap_connect() in /usr/share/nginx/www/jeedom/core/class/user.class.php on line 142" while reading response header from upstream, client: 192.168.56.1, server: , request: "POST /core/ajax/user.ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.56.101", referrer: "http://****/jeedom/index.php?v=d&p=administration"```

version	1.188.0
I use the VM provided by Loic here :
https://jeedom.fr/blog/?p=873

thanks,
Matteo

**Comment by zoic21** [comment]
Hi,

You need to install php5-ldap on VM
