### ISSUE TITLE
JSON RPC2 API Problem

### ISSUE THREAD

**Issue by msantang78** [jeedom/core#144]
The jeedom json rpc2 api only works with your php client implementation. I try other php and js implementations and i cant make it work. After looking deeper in the code i found that you use the post field "request" instead of send and receive json in raw post data.

**Comment by zoic21** [comment]
Hi,
I make a fix in last beta can you check if it's ok ?

**Comment by rd2b** [comment]
Hi,

Didn't tried yet but this is exactly the error i faced while using it with a python client.
I need to send in the "request" rather than post data.
The fix should do the trick.
Thx

**Comment by msantang78** [comment]
thanks!
