### ISSUE TITLE
Erreur de connexion LDAP

### ISSUE THREAD

**Issue by wolfyzvf** [jeedom/core#155]
Lors de l'installation par défaut de jeedom il est impossible de connecter celui-ci à un LDAP car le paquet php5-ldap n'est pas dans la liste des prérequis installés par le script install.sh (ligne 380).

Erreur :
Une erreur 500 est affiché lors du test de la configuration dans l'interface web
Et l'erreur dans /usr/share/nginx/www/jeedom/log/nginx.error : 
2015/09/01 23:36:44 [error] 676#0: *4395 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function ldap_connect() in /usr/share/nginx/www/jeedom/core/class/user.class.php on line 142" while reading response header from upstream, client: 192.168.40.1, server: , request: "POST /core/ajax/user.ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "jeedom.home.local", referrer: "http://jeedom.home.local/index.php?v=d&p=administration"

Resolution : 
Installation du paquet php5-ldap
apt-get install php5-ldap

**Comment by wolfyzvf** [comment]
Duplicate of : https://github.com/jeedom/core/issues/130
Le script d'installation devrait installer le paquet pour éviter les problèmes futurs.

**Comment by wolfyzvf** [comment]
Just in case, I leave the diff to be include in the install.sh

diff -u install.sh.orig install.sh
--- install.sh.orig	2015-09-01 23:42:48.000000000 +0200
+++ install.sh	2015-09-02 00:00:19.000000000 +0200
@@ -384,6 +384,7 @@
     apt-get -y install php5-fpm
     apt-get -y install php5-json
     apt-get -y install php5-mysql
+    apt-get -y install php5-ldap
     apt-get -y install php-pear
     apt-get -y install python-serial
     apt-get -y install systemd

**Comment by zoic21** [comment]
Hi,
Thank for return, I just add php-ldap to install
