### ISSUE TITLE
Weeks grouping in graphic doesn't take good time ranges

### ISSUE THREAD

**Issue by NikoScotch** [jeedom/core#2014]
When using a graphic grouping per week, e.g. "max value per week", it seems that the time ranges are not good. Example see the picture below : the upper graphic is the normal plot of the command, and the lower graphic is the max per week graphic of the same command.
![image](https://user-images.githubusercontent.com/77047829/169114910-6d8c8c74-25d9-406f-9f3d-22f7752796e9.png)
2 values are wrong on the lower graphic : n°5 (should be close to 0kwh) and n°9 (should be lower than n°8).
My config : 
![image](https://user-images.githubusercontent.com/77047829/169115676-d832f676-b742-4332-8b67-4ba0a430af50.png)

**Comment by NikoScotch** [comment]
Here are the values of the command, if it can help to understand what is happening....
[[Gestion_Jeedom][SuiviConso][PAC_Semaine].csv](https://github.com/jeedom/core/files/8719270/Gestion_Jeedom.SuiviConso.PAC_Semaine.csv)

**Comment by KiboOst** [comment]
Sorry but don’t see any problem here. 
also you should post issue on Jeedom community, and may have more answers.
