### ISSUE TITLE
Rendre compatible avec la PSR2

### ISSUE THREAD

**Issue by laibulle** [jeedom/core#231]
Le projet actuellement structuré ne suit pas du tout les conventions PHP de ces dernières années. Il faudrait mettre les classes dans un dossier src supprimer le suffixe .class ajouter un namespace et commencer par une majuscule. (Et supprimer les includes bien sûre).

Benefice:
Code plus lisible
Code réutilisable
Possibilité de faire des tests unitaires
Plus d'include dans les fichiers puisque l'autoloader de composer va s'en charger
Code plus robuste

**Comment by zoic21** [comment]
Le projet ne suis pas le PSR2 mais il a bien un systeme d'auto-inclusion il y a un seul fichier a inclure qui s'occupe de tout lorsque l'on demande les classes. Le travail la dessus est trop lourd pour l’intérêt...

**Comment by laibulle** [comment]
Je vais regarder plus en detail le code pour voir l'ensemble des impacts mais honnêtement c'est compliqué de travailler sur des systèmes qui ne suivent pas ces conventions. Il faut systématiquement s'adapter, ça prend énormément de temps de rentrer dans le code. On l'impression de faire du Wordpress.

**Comment by zoic21** [comment]
En faite rien de compliqué ya pas de question a se poser tu veux rajouter une class tu ajoute ton fichier nom_class.class.php dans core/class et c'est tout quand tu auras besoin de ta class il va automatiquement la charger.

**Comment by laibulle** [comment]
Oui j'ai vue mais c'est quand même pas super top.

**Comment by zoic21** [comment]
Ca répond au besoin et c'est maitrisé donc pour moi c'est largement suffisant
