### ISSUE TITLE
Blocage d’une requête multiorigine (Cross-Origin Request)

### ISSUE THREAD

**Issue by fanfounet** [jeedom/core#2319]
Pour une utilisation de l'API jsonRPC avec fetch il y a une erreur de blocage de requete. même si `header("Access-Control-Allow-Origin: *"); existe il faut maintenant ajouter :
``header("Access-Control-Allow-Methods: POST, GET");
header("Access-Control-Allow-Headers: Content-Type");`
Est-ce possible d'ajouter cette correction au core jeedom ?

**Comment by zoic21** [comment]
Bonjour,
Peux tu nous faire un PR sur le core pour qu'on puisse étudier cela ?

Merci d'avance
