### ISSUE TITLE
Erreur sur la branch beta

### ISSUE THREAD

**Issue by laibulle** [jeedom/core#232]
Lorsque j'essaye d'activer le plugin Gmail sur la branche beta, j'ai ce message sur la page 

[MySQL] Error code : 22007 (1292). Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastrun' at row 1.

**Comment by zoic21** [comment]
Bonjour,
Il faut voir directement avec le dev, ce n'est pas un plugin officiel.

**Comment by laibulle** [comment]
OK
