### ISSUE TITLE
Déclencheur provoqué lance un scénario alors qu'il ne devrait pas

### ISSUE THREAD

**Issue by ddelec24** [jeedom/core#2330]
Version jeedom: **latest 4.3.19**

Bonjour la team,

Suite à une remonté d'un bug pour un de mes plugins, il s'avère que cela relève du core. Noodom a aussi reproduit le phénomène avec un virtuel et ça le fait avec les autres plugins que j'ai pu testé.

Explication:  
Lorsqu'on utilise un déclencheur provoqué dans un scénario, exemple: `#[Maison][SignalMessenger][Message reçu]# == "toto"` mais que la valeur de notre commande info est un simple point d'exclamation ou un/plusieurs point d'interrogation, il confirme la condition alors que ça n'est pas égal à la valeur attendue

CF: [Community jeedom](https://community.jeedom.com/t/un-caractere-special-recu-semble-declencher-nimporte-quel-evenement-du-plugin-signal/114191/6?u=ddelec24)

Merci!

**Comment by zoic21** [comment]
Bonjour,
C'est normal il faut mettre === au lieu de == pour eviter ce genre de comportement.

**Comment by ddelec24** [comment]
![image](https://github.com/jeedom/core/assets/3704897/f6f532e0-9624-4933-bac1-53b8a14b0a8c)

J'avais aussi testé l'égalité stricte.
j'envoi un point d'exclamation ou un point d'interrogation dans discord et le scénario est lancé alors qu'il y a bien ===
