### ISSUE TITLE
Gestion d'un DNS perso qui pointe sur l'ip locale mais reconnu comme accès externe

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#2343]
Bonjour,

Pour accéder à mon serveur perso avec Jeedom dessus, j'utilise une URL de type "homeserver.mon-domaine.com/jeedom/", avec le DNS homeserver.mon-domaine.com qui pointe vers l'ip locale du serveur 192.168.1.X
Dans la config réseau de Jeedom, je mets "homeserver.mon-domaine.com" dans le champ host de l'accès interne.

Cependant quand un plugin appelle la fonction `network::getNetworkAccess('auto')` pour arriver à générer par exemple une url, cela détecte que je suis en extérieur et renvoie la config réseau externe de Jeedom.

En regardant les class de Jeedom, je remarque que la fonction getNetworkAccess() appelle getUserLocation() pour le mode auto.
Puis dans getUserLocation(), la variable $jeedom_ip récupère bien mon host "homeserver.mon-domaine.com", et le "if" suivant qui vérifie que c'est en forme d'IP renvoie donc "external" en résultat vu que ce n'est effectivement pas une IP.

Du coup pour palier à cela et sans changer tout le fonctionnement actuel de getUserLocation(), est-ce que l'on ne pourrait pas envisager le code suivant dans getUserLocation() avant les autres if:

`if (!filter_var($jeedom_ip, FILTER_VALIDATE_IP) && config::byKey('internalAddr', 'core', '') === $jeedom_ip) {
        return 'internal';
}`

Ce qui permettrai de gérer exclusivement le cas d'un DNS perso en accès interne quand celui-ci est renseigné dans la config réseau de Jeedom comme interne.
A moins qu'il y ait une meilleure solution que je n'ai pas envisagée.

Merci :)

**Comment by zoic21** [comment]
Bonjour,
Je viens de regarder mais je comprend pas trop un jeedom avec un dns au lieu d'une ip en réseaux interne risque de pas très bien marcher... Jeedom et les plugins on souvent besoin d'une ip en interne pour fonctionner correctement.

**Comment by spyjo** [comment]
Bonjour Loïc,
C'est courant d'avoir un DNS interne pour appeler un serveur, "monserveur.local", "monserveur.domain.com", ... au lieu de l'IP locale directement, mais ça pointe bien sur une IP locale à la fin.
C'est pour ça que la logique actuelle de la fonction getUserLocation(), qui dit que dès qu'elle match une url autre qu'une IP est forcément un appel externe, n'est pas forcément valide ;)

**Comment by edgd1er** [comment]
Bonjour,
Adguard ou pihole sont deux serveurs dns très faciles a mettre en place pour un particulier.
Sans avoir de dns privé, avec le dhcp, la box sait résoudre les noms + domain local de tous les clients dhcp.
D'ailleurs quand jeedom est dans un conteneur,  faut il  mettre l'adresse du conteneur, qui si elle est renvoyé au client web ne correspond a rien en mode bridge (172.16.a.b) ou bien mettre l'adresse locale externe (192.168.x.y) qui ne sert pas pour le conteneur. Comment est utilisée cette adresse interne ?

**Comment by spyjo** [comment]
Je te rassure il n'y a pas de confusion sur cette partie de configuration de Jeedom de mon coté :) pour info je ne suis pas en https sur mon accès local, je suis sous Nginx avec pas mal d'autres trucs hostés à coté d'où le sous-dossier pour Jeedom.

Mais tu oublies un 3ème cas:
- les plugins qui ont besoin de générer une URL pour appeler un fichier coté client (un retour de callback, une iframe...) et qui se servent donc de la fonction `network::getNetworkAccess('auto')` non pas pour un simple appel réseau ip:port, mais bien pour générer une url complète http(s)://host|ip:port/folder/ avec ce qui est configuré.

Donc pour moi c'est toujours bien utile de pouvoir configurer protocole / host / port / folder.

Mais le bug que je remonte, c'est juste que peu importe que je configure l'IP 192.x ou le dns dans la config réseau Jeedom interne, getUserLocation() pose soucis car quand Jeedom est appelé par un DNS, cette fonction considère que c'est obligatoirement un accès externe, et getNetworkAccess('auto') va donc retourner une url externe pour le plugin qui l'a appelé, ce qui est faux dans ce cas précis.

**Comment by zoic21** [comment]
Bonjour,

Ok pour le cas d'une iframe malheureusement j'ai aussi le cas inverse, le plugin jeezigbee qui peut ouvrir l'url de l'interface de z2m, si tu es en https interne il va te faire un truc du genre https://dns:8080 sauf que ca va pas marcher ca...

Pour ton code désolé pour moi il est pas valide et va amener plus de soucis que autre chose :
```
$jeedom_ip = self::getNetworkAccess('internal', 'ip', '', false);
if (!filter_var($jeedom_ip, FILTER_VALIDATE_IP) && config::byKey('internalAddr', 'core', '') === $jeedom_ip) { 
   return 'internal'; 
}
```

Déjà a aucun moment tu regarde l'ip du client (qui est la seul info sur le client qu'on a pour savoir si il vient de l'interne ou externe, ensuite cette partie la `config::byKey('internalAddr', 'core', '') === $jeedom_ip` va être vrai que tu viennes de l'interne ou de l'externe.

Par contre je vais poussé un changement pour testé si l'ip du client correspond au réseau local ca devrait corriger ton soucis.

**Comment by spyjo** [comment]
D'accord merci Loïc 👍
