### ISSUE TITLE
Issue with alerts when using calculated item (with variables)

### ISSUE THREAD

**Issue by DidouJazz** [jeedom/core#2368]
Hi,

First T**HANKS a million** for all your hard work.

I discovered an issue when using an **alert** in combination with a **caluclated item**.
Here is the calulated item I am using :
#[Maison][Maison PDL][Consommation Mois]# * variable(Prix_KWh) + variable(Prix_Abo)

Here is the configuration extract (for reference):
{"calcul":"#3130# * variable(Prix_KWh) + variable(Prix_Abo)","returnStateValue":"","returnStateTime":"","updateCmdId":"","minValue":"","maxValue":"","timeline::enable":"0","timeline::folder":"","influx::enable":"0","influx::namecmd":"","influx::nameEq":"","influx::nameVal":"","interact::auto::disable":"0","calculValueOffset":"","historizeRound":"0","jeedomCheckCmdOperator":">","jeedomCheckCmdTest":"","jeedomCheckCmdTime":"","isHistorizedCalc":"0","historizeMode":"max","historyPurge":"","denyValues":"","repeatEventManagement":"never","jeedomPushUrl":"","alert::messageReturnBack":"0","actionCheckCmd":[],"jeedomPreExecCmd":[],"jeedomPostExecCmd":[]}

 Here is the extract of the #value# value:
#3130##variable(Prix_KWh)##variable(Prix_Abo)#
We can see than the than the two operaotrs (+ and -) has been removed.

I think that, when setting the "Warning" alert it use the value above and then return another value than the one expected.

**Workaround**: I created a second "info" based on this one (without any caluculation) and then set the warning alert on this new item. This workaround is accpetable for me. 

Thanks again for your huge work,
David

**Comment by Salvialf** [comment]
Hi there, 
After various tests I can confirm that everything works as expected whether it is in terms of calculation or warning/danger alerts.
It is quite normal that operators do not appear in the "value" field because it only indicates the elements (between hashtags) that will update the value of the command.
