### ISSUE TITLE
[FEAT] Revoir moteur de cache

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2416]
Revoir le moteur de cache de jeedom, actuellement c'est un cache fichier avec un filesystem monté en ram. La librairie utilisée n'est plus maintenu il faut donc le revoir. La grosse contrainte et que le cache actuellement n'a pas de limite de taille. Piste possible : 
- redis : 
  - oblige a avoir redis qui tourne pour que jeedom marche
  - pas besoin de backup (redis gère ca lui même)
  - pas de limite de taille
  - performant
- utiliser une table in memory mariadb
  - simple a mettre en place
  - necessite un backup
  - limité en taille
  - performant

Si il y a d'autre proposition ne pas hesiter.

**Comment by an0Nym0us63** [comment]
redis me semble adapté, beaucoup de projet l'utilise, il est réputé et commun

**Comment by pifou25** [comment]
utilise redis dans un conteneur docker avec le plugin docker-manager ;)

**Comment by zoic21** [comment]
C'est encore plus compliqué que en service et ca peut vite tourner en boucle car pour que jeedom marche il faut redis, pour que le docker redis marche il faut le plugin jeedom mais pour que le plugin jeedom marche il faut jeedom qui lui a besoin de redis...

**Comment by grooverdan** [comment]
Size limits and backup make a MariaDB cache in memory hard.

Probably just best to use Aria as the more IO efficient ways to have persistence. The  page cache of the OS, unused memory, effectively makes this a in memory database for all hot cache reads. The size of the hot cache becomes a function of unused RAM.

With this you have durability of the cache.

I don't know how frequent your cache updates are so maybe even this exceeds the IO requirements.

Just my 2 thoughts as a bystander that happened to look by at this project.
