### ISSUE TITLE
[FEAT] Finir la gestion de composer sur le core

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2418]

**Comment by pifou25** [comment]
Hello ça c'est une riche idée :) 

**Objectif**

- supprimer les packages (3rdparty / vendor) du repo git et les faire installer à l'installation du core
- permettre aux plugins de piloter composer pour installer leurs propres dépendances
- autre ?

Quel est l'avancement et le reste à faire ?

**Comment by zoic21** [comment]
Bonjour,
En gros tout est bon en php8 (car pas le choix), l'idée c'est que en 4.5 je lève la limitation a php8 pour que ca se fasse en php7 aussi. 

Normalement tout est bon techniquement et sera liberé en 4.5 pour que ca soit bien testé (surtout avec des plugins utilisants des version particuliere de lib).

**Comment by pifou25** [comment]
Pour que ça marche, il faut bien maintenir à jour le composer-lock.json par rapport au composer.json sinon on a cette erreur lors de `composer install`

> #23 [vendor 6/6] RUN composer install     --no-interaction     --no-plugins     --no-scripts     --no-dev     --prefer-dist
> #23 2.519 Installing dependencies from lock file
> #23 2.546 Verifying lock file contents can be installed on current platform.
> #23 2.580 Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
> 

C'est un warning qui précède un tas d'erreurs de versions de packages, et fini par faire planter l'installation:

> #23 2.592 This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
> #23 2.592 Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
> #23 2.592 and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r
> #23 ERROR: process "/bin/sh -c composer install     --no-interaction     --no-plugins     --no-scripts     --no-dev     --prefer-dist" did not complete successfully: exit code: 4
>

**Comment by zoic21** [comment]
On peut pas simplement supprimer le composer.lock ?

**Comment by pifou25** [comment]
> On peut pas simplement supprimer le composer.lock ?

Non, il faut le tenir à jour et le versionner. C'est une bonne pratique, ça évite de subir les mises à jour non planifiées des librairies qu'on utilise.
Ensuite, tu peux soit utiliser dependabot, le bot qui va créer des PR pour proposer d'upgrader les lib composer au fil de l'eau... de préférence sur une branche beta.
Soit, tu fais manuellement un composer update régulièrement pour maintenir les librairies à jour, et tu commit les 2 fichiers composer.json & composer.lock
Dans les 2 cas, il faut incrémenter la version Jeedom. Ainsi une version de Jeedom correspond une liste définie des librairies et versions utilisées.

**Comment by zoic21** [comment]
Je comprends pas je peux aussi indiqué les versions des lib dans le composer.json, ca fait pas un peu double emploi avec le composer.lock ?

**Comment by pifou25** [comment]
Non ce n'est pas pareil :
dans composer.json tu spécifie la liste des dépendances avec une plage de versions plus ou moins large
`composer update` va résoudre ces plages au mieux, parfois en fonction des incompatibilités entre 2 lib, et fixer le résultat dans le fichier composer.lock
`composer install` fait l'installation des versions fixées dans le composer.lock et on est assuré que c'est toujours les mêmes versions.

https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by pifou25** [comment]
Par exemple il y a un problème avec le composer.json actuel: il n'est pas compatible php7.3 !
```
  Problem 1
    - symfony/http-client[v7.0.0, ..., v7.0.7] require php >=8.2 -> your php version (7.3.33) does not satisfy that requirement.
    - Root composer.json requires symfony/http-client ^7.0 -> satisfiable by symfony/http-client[v7.0.0, ..., v7.0.7].
```
Pour avoir cette erreur j'ai juste fais `composer update` dans un env en php7.3 ... évidemment avec php8.2 ça marche.
Et c'est vrai, dans packagist (qui est le gestionnaire de packages php) il faut remonter à la v5.4 pour trouver une version compatible php7.3 de cette lib:
https://packagist.org/packages/symfony/http-client#v5.4.39

**Comment by zoic21** [comment]
Bonjour,
On peut malheureusement pas faire une branche par verison de php, on a pas les ressources ni la connaissance ni la competence de gerer ca... On galere deja avec une simple version alors avec deux on va avoir des ecard, des erreurs et en plus ca posera soucis avec les plugins...

**Comment by pifou25** [comment]
On peut tout à fait créer une nouvelle branche, ça ne demande aucune compétence ni connaissance :D et puis, ça ne sera dans un premier temps qu'une nouvelle branche de dev, il ne s'agit pas de maintenir 2 branches stable simultanément. Pas pour le moment.

Après, mais c'est une autre question, il faudra évoluer sur la gestion des branches, il n'y a toujours pas de nouvelle branche alpha / beta, il n'y a plus non plus de support 4.3 puisque la branche a disparu (si je ne m'abuse) ... Mais c'est un autre sujet.

Pour Composer, en tout cas, il faut versionner les 2 fichiers composer (.json et .lock) et il en faut 1 différent pour php8 et php7...

**Comment by zoic21** [comment]
Bonjour,
Je vois vraiment pas comment on pourrait faire avec deux branche, regarde l'évidence tu le dis toi meme rien que une branche on y arrive pas alors deux j'imagine meme pas écrart. Par contre je suis étonné que dans le meme fichier composer on puisse pas mettre php7 et php8

**Comment by pifou25** [comment]
Non, 1 seule version de PHP mais on met la version minimale compatible. Donc, tant qu'on reste compatible PHP7.3 on peut laisser le même composer.json & .lock pour tout le monde -  y compris php8+ - à condition de corriger la version symfony/http-client en v5.4 c'était le seul package qui pose problème. A priori il reste compatible php8 aussi, à vérifier.

Du reste, je ne comprends pas ce qu'il fait la ce package... il n'existe même pas dans notre répertoire actuel /vendor !? on devrait pas juste le supprimer du composer.json & .lock ? A moins que tu ne l'aie rajouté spécifiquement pour php8 en remplacement d'une autre qui aurait disparu au passage ? Je n'ai pas fait la comparaison entre le composer.json et la liste des lib exitantes versionnées dans /vendor, je suppose qu'il y a d'autres écarts.

**Comment by zoic21** [comment]
Bonjour,
C'est possible, pour etre honnete je ne maitrise pas trop cette partie j'ai pris les retours du community et apparement ce package permet de corriger des soucis avec d'autre packages en php8 mais je n'ai vraiment pas assez de connaissance pour savoir si c'est vraiment utile ou non.

**Comment by pifou25** [comment]
Alors j'ai trouvé un workaround pour les packages à problème comme celui-ci: 

`"symfony/http-client": "^5.4 || ^7.0",`
Il s'installe en v5.4 pour php7.3 et en v7.0 pour php8+.
Mais, pour que ça marche il faut faire un `composer update` en php8 ce qui a pour effet de mettre à jour aussi le composer.lock alors que si on est en php7 on fait `composer install` pour l'installation / le restore.
J'ai fait ça parce qu'on a vraiment trop de notice / deprecated avec cette lib en php8...

**Comment by zoic21** [comment]
ok ca c'est gerable je pense de distinguer update et install faudra juste bien gerer tous les cas en particulier l'installation d'un jeedom en php8

**Comment by zoic21** [comment]
Fait a 90% reste juste le nettoyage des dépendances non utilisé par le core (mais faut que les plugins réintègre en interne ces dépendances avant).
