### ISSUE TITLE
Cache miss raises Error [V4.4, PHP8, Doctrine\Cache v1.13]

### ISSUE THREAD

**Issue by BadWolf42** [jeedom/core#2426]
Bonjour, je vais la faire en français, ce sera plus compréhensible.

Suite à ce thread Commu: https://community.jeedom.com/t/122712
Il a été remarqué que le Core Alpha en 4.4.2 installe Doctrine\Cache en version 1.13,
Alors que la version actuellement dans le repo est la 1.2.
Je pense que c'est "normal" pour ne pas poser de problème lors de la mise à jour 4.3 -> 4.4.

Par contre dans Doctrine\Cache v1.13, il y a un comportement étrange quand la clé accédée est en train d'être supprimée:
https://github.com/doctrine/cache/blob/56cd022adb5514472cb144c087393c1821911d09/lib/Doctrine/Common/Cache/FilesystemCache.php#L41-L45

Si la ligne 41 est passée mais la ligne 45 pas encore exécutée, et que le fichier est supprimé dans un autre thread/process, 
Alors `fopen()` retourne `false` au lieu d'une ressource, entrainant la remontée d'une erreur PHP, par ex:
```
Exception: fgets(): Argument #1 ($stream) must be of type resource, bool given
#0 /var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(46): fgets() 
#1 /var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(59): Doctrine\Common\Cache\FilesystemCache->doFetch() 
#2 /var/www/html/core/class/cache.class.php(151): Doctrine\Common\Cache\CacheProvider->fetch() 
[...]
```

Il serait intéressant de `catch(Error)` dans la classe `cache` pour les 2 appels à `self::getCache()->fetch($_key)`, afin d'éviter le problème dans le reste du code.

**Souhaitez-vous que je propose un PR dans ce sens ?**

Bad

**Comment by pifou25** [comment]
si c'est spécifique à php8 c'est plutôt à prévoir pour la prochaine version de jeedom 4.5 (mais on n'a pas encore de branche pour celle la)
La 4.4 pourrait peut être passer stable un jour si on arrête d'en rajouter non ? :D 

Après, un catch(Error) il faut toujours mettre quelque chose, même si on fait rien un log en debug pour indiquer que c'est normal. Un catch vide, c'est mal, c'est une bad practice.

**Comment by BadWolf42** [comment]
Tout à fait, 
Voici la correction que je peux proposer: https://github.com/jeedom/core/compare/alpha...BadWolf42:core:fix-php8-doctrine-cache-miss
Si vous souhaitez un PR (même à merger plus tard).

**Comment by NebzHB** [comment]
moi je dirais vas-y ;) c'est que un catch

**Comment by NebzHB** [comment]
par contre, ceci me fait un peu plus "peur" :

```
This library is deprecated and will no longer receive bug fixes from the Doctrine Project. Please use a different cache library, preferably PSR-6 or PSR-16 instead.
```

**Comment by Phpvarious** [comment]
Idem que Nebz, c'est qu'un catch... Et une issue est déja ouverte pour une future 4.5 : 

https://github.com/jeedom/core/issues/2416

**Comment by zoic21** [comment]
Bonjour,
La 4.4 est freeze donc pas posisble de corriger pour le moment. Par contre oui un try catch pourra etre ajouté après la sortie du 4.4 et avant la 4.5 qui de toute facon va completement revoir cette partie car la lib est deprecated.

**Comment by NebzHB** [comment]
Heu, Freeze ça veut dire pas de nouveauté mais bien des bugfixs...

**Comment by pifou25** [comment]
ha oui mais la c'est le 'super-freeze' ! le temps que la beta passe stable - enfin ? La sortie de la 4.4 en stable serait donc imminente :D

**Comment by BadWolf42** [comment]
Merci à tous pour vos retours.
PR créé, je vous laisse merger en temps voulu, si vous le souhaitez.
Je clos cette issue qui est de toute façon une sous-issue de la #2416.
