### ISSUE TITLE
Prevent 'changes' events being blocked when PC goes to sleep

### ISSUE THREAD

**Issue by Salvialf** [jeedom/core#2427]
Prevent javascript errors when returning to a paused tab.

![image](https://github.com/jeedom/core/assets/48010158/e7617ea3-7908-4c2c-912a-5426415d6895)

Possible solution, to be confirmed:
```js
document.addEventListener('resume', function(){
  jeedom.connect = 0;
  clearTimeout(jeedom.changes_timeout);
  jeedom.changes_timeout = null
  jeedom.changes()
})
```

**Comment by BadWolf42** [comment]
Hello,
Another way of fixing this is by using
[Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), which is a better practice for long lasting tasks on a webpage (cf https://web.dev/articles/off-main-thread), 
or a [Shared Worker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) to avoid loading the same events in multiple open pages, 
and maybe in combination of even async js.
