### ISSUE TITLE
Bugfix logs fantômes 

### ISSUE THREAD

**Issue by Babatou** [jeedom/core#2437]
cause initiale bouton Log/TOUT SUPPRIMER
Ce dernier effectue un rm 
Sauf que certains fichiers restent en statut "deleted" et ne sont pas vraiment effacés. Pire, ils continuent de se remplir
Et tant que le process reste actif, les lgos continuent de se déverser dans le fichier au status 'deleted'

**Comment by zoic21** [comment]
Corrigé dans ce #2436
