### ISSUE TITLE
Problème de dépendances et utilitaire pip3

### ISSUE THREAD

**Issue by Babatou** [jeedom/core#2442]
Je ne sais pour l'instant pas pousser de modif dans le core. Mais il apparait que 2 commandes pip2 et pip3 sont appelées sans droit sudo dans
core/system.class.php

public static function getInstallPackage($_type) {
...

Le problème est que la gestion des dépendances des modules pip ne fonctionne pas dans des cron appelés par un autre cron.

if (version_compare(self::getOsVersion(), '11', '>=')) {
return self::$_installPackage[$_type];
}

- $datas = json_decode(shell_exec('pip2 list --format=json 2>/dev/null'), true);

+ $datas = json_decode(shell_exec(self::getCmdSudo() . ' pip2 list --format=json 2>/dev/null'), true);
foreach ($datas as $value) {
self::$_installPackage[$_type][mb_strtolower($value['name'])] = array(
'version' => $value['version']

@@ -343,7 +343,7 @@ class system {
}
break;
case 'pip3':

- $datas = json_decode(shell_exec('pip3 list --format=json 2>/dev/null'), true);

+ $datas = json_decode(shell_exec(self::getCmdSudo() . ' pip3 list --format=json 2>/dev/null'), true);
foreach ($datas as $value) {
self::$_installPackage[$_type][mb_strtolower($value['name'])] = array(
'version' => $value['version']

**Comment by zoic21** [comment]
Corrigé dans le pr
