### ISSUE TITLE
[FEAT] System Queue / File d'attente core

### ISSUE THREAD

**Issue by Hotfirenet** [jeedom/core#2489]
créer un système de file d'attente principale
pour planifier l'installation de plugins
utilisable par les plugins pour séquencer et ordonnancer. 
create a core queue system
for scheduling the installation of plugins
usable by plugins

**Comment by pifou25** [comment]
common usecase for Jeedom in Docker container: when I drop the container and pull a nuw updated image, I restore my Jeedom backup; then it automatically trigger every plugins dependencies installation.

**Comment by rocket13011** [comment]
Creation of the concept and the feed engine.

**Comment by rocket13011** [comment]
Link https://github.com/jeedom/core/issues/2416

**Comment by zoic21** [comment]
Dans l'idée : 

- une fonction addToQueue(string class, string function,array args, string queue_id = 'default') qui met en cache (utiliser le même principe que le système de cache event pour garantir l'ordre) et renvoi l'id de l'élément. Une queue par queue id (il faut donc stocker quelque part la liste de toute les queues)
- un cron appelé toute les minutes  et sur chaque queue appels une sous fonction en background avec l'id de la queuee. Cette sous fonction dépile la queue et appelles les fonctions en question avec les arguments (peut être ajouter l'id l'élément pour que la fonction puisse elle même faire la suppression si besoin ?) . Si la fonction se passe bien suppression de la pile de queue de l'élément en question.

Questions : 
- comment gérer le cas ou la fonction (du plugin/core) tombe en erreur sur le traitement de l'élément de la queue ? Incrémenter un retry et au bout de 5 échecs on supprime l'élément ? Le mettre dans une sous queue et la traiter a part (dans ce cas on peut plus garantir l'ordre de traitement) ? Attention a pas planter toute le systeme de queue car on tombe sur un element intratable

Idée : 
- au lieu de gérer la queue avec un cache (qui est lourd a mettre en place avec des sémaphore pour pas écraser la valeur precedente) on peut : 
-- tout faire un fichier, avec un nom style queue_id-timestamps_ms-id.queue dans le dossier /tmp/jeedom monté en ram (aucun écriture sur disque donc). Ensuite la fonction trie les élément par queue_id et timestamps_ms, un soucis possible (mais peu probable) si 2 éléments arrivent pour la même queue la même ms (solution possible mettre une pose de 1ms a la fin de addToQueue pour l'imiter les risques)
-- une table de queue en mariadb, l'id qui s'incrément permet de garantir que les éléments sont dépilé dans l'ordre d'arriver, on peut facilement avoir la liste des queues (au lieu de le stocker quelque part). Soucis les écritures disque, on peut utiliser une table in memory (attention lors d'un redémarrage) mais dans ce cas il y a une contrainte sur la tailles des champs (arg en particulier). Pour palier a ce soucis on peut faire un fichier json écris dans /tmp/jeedom avec les arg qui a comme nom l'id de la ligne dans la db. Pour trancher il faut voir la quantité de données qui sera écrite (sachant que mariadb a des mécanisme pour limiter l'usure des carte sd donc est ce vraiment utile ?)

**Comment by grooverdan** [comment]
MariaDB 10.6, "select for update skip locked" is a way for MariaDB to function as a queue where the jobs are independent (which only partially appears the case by the google translation of this). With this lock, the cron is free to continue the task and update the record as complete (or delete) when finished. You seem to be after some ordering so the implementation details may vary.
