### ISSUE TITLE
Error JS "Vue d'ensemble des objets" et "Evénements en temps réel"

### ISSUE THREAD

**Issue by Furaxworld** [jeedom/core#2498]
**Error JS by moving the modal to the left**

`http://192.168.1.50/core/php/getResource.php?file=core/dom/dom.ui.js&md5=ab54cc40667e26f0e20937fb23745b2a&lang=fr_FR	1709	Uncaught TypeError: Cannot read properties of undefined (reading '0')`

![Animation](https://github.com/jeedom/core/assets/96196882/72be336b-b826-4805-93d6-41a01b99e981)

**Comment by zoic21** [comment]
Bonjour,
Sur quel navigateur ? Je ne reproduis pas le soucis.

**Comment by Furaxworld** [comment]
Salut,

![image](https://github.com/jeedom/core/assets/96196882/6b0caac4-4a3b-4ae1-b499-617a760d84dc)

**Comment by Phpvarious** [comment]
Bonjour,
En faite le bug est facilement reproductible, il concerne la totalité des jeeDialog /modale. Il suffit de resize en sélectionnant la partie gauche de la modale et d'aller en butée de fenêtre.

https://github.com/jeedom/core/blob/alpha/core/dom/dom.ui.js#L1709-L1710

Pour l'exemple de clientX : 
`let clientX = event.clientX || event.targetTouches[0].pageX`

`event.clientX` prend la valeur 0 dans ce cas, et est considéré comme `false` donc `event.targetTouches[0].pageX` est retenu mais il n'existe pas en version "desktop"

Idem pour le clientY

Sur mon alpha, j'ai fait quelques test, en remplaçant par
`let clientX = (typeof event.clientX == 'number') ? event.clientX : event.targetTouches[0].pageX`

J'ai pas fait de PR, car je sais pas si la méthode est propre.

**Comment by zoic21** [comment]
Bonjour,
Je pense ta correction est bonne, il y a effectivement un cas limite ou il prend pas ce qu'il faut tu peux faire ton PR.

**Comment by Furaxworld** [comment]
Salut,

Testé  et plus d'erreur JS.
Merci @Phpvarious ,
