### ISSUE TITLE
Error SQL in database check

### ISSUE THREAD

**Issue by Furaxworld** [jeedom/core#2524]
Salut,

Erreur dans la vérification de la base de donnée (Atlas?) 
Version : 4.4.3
Source : default
Branche : V4-stable
Système : Atlas
Debian: 11.9
Database: 10.5.23-MariaDB-0+deb11u1

![image](https://github.com/jeedom/core/assets/96196882/8ec6af30-b79b-44e4-aafb-5c1d0639a706)

`ALTER TABLE `cmd` DROP INDEX `logicalID`; CREATE INDEX `logicalID` ON `cmd` (`logicalId` ASC);`

Cette commande essaie de supprimer un index nommé logicalID de la table cmd, puis de créer un nouvel index portant le même nom sur la même table et la même colonne!

**Comment by zoic21** [comment]
Bonjour,
C'est normal cette partie est pour Debian 12, l'erreur en 11 était bien prévu il ne faut pas s'en préoccuper j'ai juste pris un peu d'avance sur les futurs évolution de l'os.
