### ISSUE TITLE
[FIX] Clone eqLogic => handle new cmd id

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2540]
When we clone eqLogic some information are link to old cmd id (of eqLogic source), need to be replace with new cmd id (from clone result eqLogic) like information field for graph in widget background

**Comment by Mips2648** [comment]
Hello,
Apart backgraph cmdId which I propose to fix in https://github.com/jeedom/core/pull/2727, do you have another case in mind for this issue?

**Comment by zoic21** [comment]
Only one I can see it's maybe case like virtual plugin do calcul with cmd. It's a special case sometime it's needed sometime not... So we can close this issue when PR is merge for me.
