### ISSUE TITLE
erreur JS " Maximum call stack size exceeded" lors de l'affichage de graphique 

### ISSUE THREAD

**Issue by Furaxworld** [jeedom/core#2541]
`http://192.168.1.50/core/php/getResource.php?file=core/js/history.class.js&md5=2f44f06582d37ee9ed5b97ec0fc77c34&lang=fr_FR	1576	Uncaught RangeError: Maximum call stack size exceeded`

**Comment by zoic21** [comment]
Bonjour,
Je pense pas que ca soit corrigeable, ya trop de valeur sur le graph a afficher et lors de la recherche de la plus petite et plus grand valeur le navigateur dit stop c'est trop....
