### ISSUE TITLE
[FEAT] Add a repo component Git that only uses native git / Ajouter un composant repo Git qui utilises que des commandes natives git

### ISSUE THREAD

**Issue by an0Nym0us63** [jeedom/core#2567]
Permettra detre facilement comaptible avec gitlab ou azure & CO

En utilisant une autre classe repo sans toucher l'ancienne on aura un autre mode et la transition pourra etre douce.

**Comment by pifou25** [comment]
Hello, je ne comprends pas l'intérêt de cette suggestion, tu pourrais détailler ce qui pourrait être compatible entre un système domotique et un système de gestion de code ? et / ou un cloud ?
Aussi, pour info on a un "plugin" non officiel qui permet d'afficher des repo github sous forme de plugins à ajouter - genre comme le market - Je pense que ta suggestion pourrait prendre la forme d'un plugin Gitlab ou un plugin Azure. cf le [plugin Alternate Market](https://github.com/NextDom/plugin-AlternativeMarketForJeedom)

**Comment by Hotfirenet** [comment]
Salut @pifou25 c'est justement la question qui se pose, on se dit qu'il serait plus généraliste d'avoir une nouvelle classe dédié a GIT. 
ce qui permet justement une compatibilité avec github, gitlab ou encore Azure DevOps.
