### ISSUE TITLE
Ajout d'un mode wizard pour simplifé la configuration d'un plugin

### ISSUE THREAD

**Issue by mika-nt28** [jeedom/core#258]
Une idée qui m'a été soufflée par les utilisateurs du plugin EIB / KNX, est la création d'un mode wizard (ou un mode de configuration pas à pas).
Cela existe pour la création d'un scénario, pourquoi pas porté l'idée sur les plugins qui peuvent être complexe a paramétrer.

Pour moi le mode wizard doit ce décomposée comme ceci:
1- Nom et mode wizard
2- Paramètre spécifique au plugin => via une page wizard.php 
3- Paramètre spécifique a jeedom (type, sous type, retour d’état si type 'action')
4- Choix du widget

**Comment by zoic21** [comment]
Bonjour,
J'ai bien eu la demande pour l'instant je ne vois pas comment faire ca générique et facile et j'ai trop de truc a faire avant. Mais je garde l'idée.

**Comment by mika-nt28** [comment]
oui c'est pour ne pas perdre l'idée que j'ai ajoutée au github l'idée.
J'ai commencé a regardé comment l'intégrer au core de jeedom.
Si j'arrive a un résultat je te l’enverrais

**Comment by zoic21** [comment]
Dans l’immédiat cela me semble compliqué vu la diversité des plugins. Mais je garde l'idée.
