### ISSUE TITLE
[FIX] Réintroduire les dépendances composer pour utiliser le client natif influxdb dans jeedom 4.4

### ISSUE THREAD

**Issue by pbrinette** [jeedom/core#2599]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**

La déclaration des dépendance composer pour utiliser les fonctionnalités inflluxDB native a été supprimé dans la version Jeedom 4.4. 

Suite à  la migration de jeedom 4.3.23 à 4.4.5, j'ai eu des messages d'erreur du type : 

````
Erreur sur eibd::BusMonitor() : Class 'InfluxDB\Client' not found 
````

Cette fonctionnalités avait été supprimée lors du passage de Jeedom 4.2 à 4.3 pour finalement être réintégrée dans la version 4.3.8.

Elle ont disparue à nouveau de composer : 
https://github.com/jeedom/core/commit/bfbf37a4c158679415c745345855f3b4b8965a44#diff-9c5d32ec0a62c954c9e20b3fb8006b4a6f0b8325fa7ff5529a98c0c30c679346L42

**Décrivez la solution que vous souhaitez**

Réintroduire les déclarations dans `vendor/composer` liées au client **influxdb** qui ont été supprimées dans le commit bfbf37a4c158679415c745345855f3b4b8965a44 

**Décrivez les alternatives que vous avez envisagées**

J'ai appliqué manuellement les modification dans mon arborescence jeedom :
 
J’ai donc rajouté dans le répertoire `vendor/composer` les références à influxdb qui ont été supprimé des fichiers `autoload_psr4.php`, `autoload_static.php` et `installed.json` .
 
Je n'ai plus constaté d'erreur suite à ces modification et ma base influxdb est alimentéee correctement.

**Comment by zoic21** [comment]
Bonjour,
C'est pas si simple, la lib utilisée était celle ci il me semble : https://packagist.org/packages/influxdb/influxdb-php mais elle n'est plus maintenu. Je pense que le mieux serait de sortir cette partie influxdb du core pour la laisser a un plugin qui sera plus flexible sur la gestion des dépendances.

**Comment by pbrinette** [comment]
Bonjour @zoic21.
J'essaye de me renseigner, mais il me semble que le plugin InfluxDB disponible sur le market utilise bien la lib influxdb/influxdb-php v1.15.2 qui est la dernière disponible.
Etant donné que le client Influxdb est une fonctionnalité native disponible dans jeedom core (Il y a encore tout les champs de configuration dans les différents interfaces d'admin), je trouve dommage de devoir passer par un plugin juste pour pouvoir réactiver cette fonctionnalité.

**Comment by zoic21** [comment]
Bonjour,
Je comprends mais j'ai actuellement aucune dispo pour ca et personne de l'équipe n'a de la dispo... Malheureusement c'est trop peu utilisé pour que ca soit une priorité.

**Comment by Hotfirenet** [comment]
Bonjour @pbrinette, 
tu peux faire un PR si tu as une solution viable.

Il faut voir si il y a encore un intérêt de garder cette fonctionnalité dans le core.

**Comment by pbrinette** [comment]
Je comprend l'idée de ne plus utiliser une librairie qui n'est plus maintenu. 

Le passage passage de la librairie [influxdb-php (client Influxdb V1)](https://packagist.org/packages/influxdb/influxdb-php)  à la libraire [influxdb-client-php (client Influxdb V2)](https://packagist.org/packages/influxdata/influxdb-client-php) nécessiterai un peu de travail. CF: [Exemple de code compatible v1.8](https://github.com/influxdata/influxdb-client-php/blob/master/examples/InfluxDB_18_Example.php)

En ce qui me concerne, j'ai juste réinstallé l'ancienne libraire avec la commande : 
```
$ cd /var/www/html
$ composer require influxdb/influxdb-php
```
Cette solution répond à mon besoin.

Il serait bien d'indiquer dans la prochain [changelog](https://doc.jeedom.com/fr_FR/core/4.4/changelog) de la version stable que le la libraire n'est plus installé, et que ceux qui ont toujours besoin de cette fonctionnalité peuvent l'installer manuellement avec la commande si dessus.

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour j'ai mis a jour la documentation jeedom suite a vos remarques
