### ISSUE TITLE
[BUG] Removing MariaDB iblogfile* in the entrypoint is a sure way to corrupt a users data

### ISSUE THREAD

**Issue by grooverdan** [jeedom/core#2602]
**Décrire le bogue**

iblogfiles are the mechanism that allows MariaDB to recovery during crash recovery. If they contain DDL changes the data afterwards will not be recoverable.

There is no official documentation (mariadb.com/kb) describing this as a sane thing to do.

Later versions of MariaDB won't start with these files removed.

**Reproduire**
Etapes pour reproduire le comportement :

1. Alter a table
2. immediately shut down the container
3. remove the iblogfile*
4. start container

**Expected behavior**

remove lines install/OS_specific/Docker/init.sh#L67-L70

and display the mariadb error log if the service fails

**Screenshots**/**Additional context**

From https://jira.mariadb.org/browse/MDEV-34047

**Comment by grooverdan** [comment]
Probably should be a new feature (but I was too lazy) - a service manage entry point where multiple services are within a container is best practices - https://github.com/docker-library/official-images/?tab=readme-ov-file#init - this allows services like MariaDB to get a forwarded TERM signal rather than just being KILLed after processes are still there after cron is killed.

**Comment by zoic21** [comment]
Hello,

We remove ib_logfile only if database can't start, it's fix lot of issue. I can review that, maybe there is change on new mariadb.

**Comment by grooverdan** [comment]
Cannot start could be anything from a permission denied, out of memory, and existing instance still running (different container same datadir) or many other cases. There may be times in the past where the ib_logfile was effectively empty where deleting had no meaningful effect. With any alter table or changing DDL, there is a new tablespace id that only exists in the redo log and as a result entire tables can be removed if the redo log is removed.

There have been a significant amount of fixes on fixing corruption and other issues in data recovery over the last 5 years so its less likely to be the problem now.

As a documentation reference - red comment at top: https://mariadb.com/kb/en/innodb-redo-log/

**Comment by grooverdan** [comment]
Thank you.
