### ISSUE TITLE
[BUG]  API pour piloter le thermostat Google Nest depuis Jeedom.

### ISSUE THREAD

**Issue by brainybiz** [jeedom/core#2635]
En 2016, il existait une API pour piloter le thermostat Google Nest depuis Jeedom. Google a par la suite fermée cette API. L'accès aux API de Google a maintenant évoluée.
https://developers.home.google.com/apis?hl=fr
https://developers.google.com/nest/device-access/api?hl=fr
Serait il possible de mettre à jour le plugin avec la nouvelle API Google ?
Plusieurs clients ont des thermostats Nest qui ne communiquent plus avec Jeedom actuellement.

**Comment by zoic21** [comment]
Bonjour a vous aussi (3eme fois quand meme) !!!!!!
Cette demande n'a rien a voir avec le core, merci de ne pas utiliser les issue du core pour des demande sur des plugins.
