### ISSUE TITLE
Plugin pour Interphone Akuvox

### ISSUE THREAD

**Issue by brainybiz** [jeedom/core#2636]
Akuvox propose des interphones SIP très ouverts, pour des usages résidentiels ou collectifs. 
Akuvox propose une API, afin qu'un équipement tiers puisse communiquer avec. 
Serait il possible d'avoir un plugin pour que Jeedom puisse ouvrir la porte d'un interphone Akuvox ?

**Comment by brainybiz** [comment]
documentation des API d'Akuvox : https://knowledge.akuvox.com/docs/integration-with-third-party-device-14

**Comment by zoic21** [comment]
Bonjour a vous aussi !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Cette demande n'a rien a voir avec le core, merci de ne pas faire de demande de plugin sur des issues du core !!!!!!
