### ISSUE TITLE
Apport d'éclairage artificiel, en fonction d'une consigne et des lux mesurés

### ISSUE THREAD

**Issue by brainybiz** [jeedom/core#2637]
Serait il possible de disposer d'un plugin qui permette de faire à un apport d'éclairage artificiel de 0 à 255, en fonction de la consigne demandée par l'utilisateur et le lux mesurés par un capteur de luminosité. 
Exemple : 
Si la consigne utilisateur est de 300 lux et que la luminosité mesurée est de 200 lux, faire un apport de 100 lumens de lumière artificielle.

**Comment by zoic21** [comment]
Bonjour a vous aussi !!!!!

Cette demande n'a rien a voir avec le core, il est deja possible de faire ca simplement avec un scénario et nous n'avons malheureusement pas les ressources disponible pour nous lancer la dedans avec un plugin.
