### ISSUE TITLE
[BUG] Remove max size of list widget (limit to 100px on disign)

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2647]
![image](https://github.com/jeedom/core/assets/1536036/ec5f4810-7f5e-4dd9-aadf-437d3488ea65)

**Comment by Furaxworld** [comment]
Salut,
En mettant `width: 100%` dans desktop.main.css ça conviendrait ? 
`  [data-page="plan"] div[data-subtype=select] {
    min-width: unset !important;
    width: 100% !important;
  }`

![image](https://github.com/jeedom/core/assets/96196882/13befaea-d4d2-4d9a-9169-6a4f92c893b8)

**Comment by zoic21** [comment]
Salut,
Oui je pense au moins ca n'impact pas le dashboard seulement les designs.

**Comment by Furaxworld** [comment]
#2649
