### ISSUE TITLE
[BUG] Issue with long polling and page refresh that hanging browser

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2650]
Ajax event request work with long polling when you click to change page or refresh page browser wait and of long polling request.

Maybe related to https://stackoverflow.com/questions/48349073/slow-page-refresh-in-chrome-with-ajax-long-polling

Some test : disable jeedom.change, page speed up and refresh also. For test I also replace ajax change code by : 

```
if (init('action') == 'changes') {
  sleep(10);
  ajax::success();
  //ajax::success(event::changes(init('datetime', 0), 59));
}
```

It's like fetch request in ajax https://github.com/jeedom/core/blob/alpha/core/dom/dom.utils.js#L568 are not run in same time and browser wait and of all request before do something.

**Comment by zoic21** [comment]
It's not fix the issue but it's force to close all current fetch request

**Comment by zoic21** [comment]
<img width="952" alt="image" src="https://github.com/jeedom/core/assets/1536036/710a3211-85ac-426a-bcb5-b6dd654151b5">

We can see fetch is immediatly call but seem to wait reponse from all current fetch before execute then (in this exemple I have add a 10s sleep on jeedom change)

**Comment by zoic21** [comment]
This bug not affect all jeedom.... You can try to reproduct by add this line  : `sleep(10);` here https://github.com/jeedom/core/blob/alpha/core/ajax/event.ajax.php#L30 (just before line 30 : `ajax::success(event::changes(init('datetime', 0), 59));` ). After that go to your jeedom load page and immediatly try to reload page you can see it will be very slow.

**Comment by TiTidom-RC** [comment]
Hi,

after upgrading to the last alpha from the version on may 5th, my jeedom is very very slow on loading every pages.

After changing "event.ajax.php" and comment the `ajax::success(event::changes(init('datetime', 0), 59));`, (replaced with only `ajax:success();` Jeedom is back to running at normal speed and pages are no longer loading slowly !

`if (init('action') == 'changes') {
    sleep(1);
    ajax::success();
    // ajax::success(event::changes(init('datetime', 0), 59));
}`

**Comment by TiTidom-RC** [comment]
Hi @zoic21,

After removing all IPv6 DNS entries for those Jeedom, all is working fine now. So the problem is with IPv6 (and fetch ? ajax ?) since last versions (after beginning of May).

Have a nice evening.

**Comment by zoic21** [comment]
Hello,

I test on my side but it's not solved the issue....

**Comment by TiTidom-RC** [comment]
if you need other tests, don't hesitate.

**Comment by Loic-Fournier** [comment]
I tried replacing `ajax::success(event::changes(init('datetime', 0), 59));` by `ajax::success()`

=> It fixes the issue (Jeedom is fast again) BUT it spams event.ajax (check in console => network) like HELL !
![spam_event](https://github.com/jeedom/core/assets/100291010/504f0611-fe42-4822-acdf-51ced0879937)

So it is definitly not a good solution

**Comment by zoic21** [comment]
Fix by :
- https://github.com/jeedom/core/commit/bc16446d4f9d0d059e274da8ecd35649eefb33c9
- https://github.com/jeedom/core/commit/9f47990a6794e4d9e2224a18192f42780271d13f
- https://github.com/jeedom/core/commit/33671de94375b6ad550a2b92b5add132c662f3a9
