### ISSUE TITLE
Hardcoded history purge boundaries

### ISSUE THREAD

**Issue by BadWolf42** [jeedom/core#2652]
**Describe the bug**

`2025-01-01 01:00:00` is hardcoded in history purge, see: 
https://github.com/jeedom/core/blob/3b43510fe1011175ed3d7e02cf1b36bcae6fba26/core/class/history.class.php#L220-L223

**To Reproduce**
After `2025-01-01 01:00:00`, all new history will be purged during archive...

**Expected behavior**
`2025-01-01 01:00:00` should not be hardcoded, but calculated on the spot with something like:
`DATE_ADD(NOW(), INTERVAL 1 YEAR)`

**Comment by BadWolf42** [comment]
Hello and thank you for the answer,

Ok, I get the idea and seen commit https://github.com/jeedom/core/commit/bac551f5dd7acb302e71f262ac7375ad3548aca3, that temporarily fixes this issue.

But so many other things will go wrong if date/time is not ok, wouldn't it be better to simply avoid any time related operation (and this cleanup) if clock is wrong?

By the way, in 2025, these lines may also need to be pushed by 1 year:
https://github.com/jeedom/core/blob/bac551f5dd7acb302e71f262ac7375ad3548aca3/core/class/jeedom.class.php#L1038-L1041

Bad

**Comment by pifou25** [comment]
I event don't understand why we should care about such fixed hard-coded dates... ?

(rappelez-vous le bug de l'an 2000... on ne devrait jamais avoir de dates en dur dans nos programmes, sinon évidemment ça nous oblige à les éditer chaque année et je ne vois pas l'intérêt)

**Comment by zoic21** [comment]
A got lots of issue due to the date specially on rpi, frequently rpi boot in 2020/2021... and don't take ntp update. Same on some start that boot un 2027.

Only way I find is this one, stop all relative execution if date is not ok is to hard and need lots of check and operation (big impact on performance).

**Comment by BadWolf42** [comment]
"fixed" by commit bac551f
