### ISSUE TITLE
[BUG] clean timeline ne fonctionne plus avec php8.0

### ISSUE THREAD

**Issue by Ultraboss77** [jeedom/core#2663]
**Décrire le bogue**
Une exception SQL "SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens" est levée tous les jours à l'heure du cronDaily jeedom.
En cause la fonction clean de timeline.class.php

**Reproduire**
installer php8.0 ou plus
Depuis php8.0, les erreurs sur les PDO ne sont plus silencieuses.
Or le soucis de la fonction clean de timeline.class.php est qu'on appelle une requête sql en voulant binder le paramètre pour l'argument LIMIT.
Mais la fonction &Prepare de DB.class.php de permet pas d'utiliser bindParam pour forcer le type PDO::PARAM_INT avant d'appeler execute, qui ne prend et passe des paramètres uniquement de type string : https://www.php.net/manual/fr/pdostatement.execute.php
L'exception se produit car on appelle execute avec un paramètre qui n'est pas définit dans la requête sql.

**Comportement attendu**
Plus d'erreur dans http.error et nettoyage des éléments de la timeline ok
Je propose cette réécriture dans la fonction clean :
```
//     $values = array(
//     'number' => $delete_number, // inutile du coup
//     );
     $sql = 'DELETE FROM timeline ORDER BY `datetime` ASC LIMIT '.$delete_number;
     DB::Prepare($sql, array(), DB::FETCH_TYPE_ROW);
```
Le risque est quand même assez faible de réaliser une injection via le paramètre timeline::maxevent, mais il faudrait au moins verrouiller le champ :

**Captures d'écran**
![image](https://github.com/jeedom/core/assets/41824575/576290ff-6f11-4688-b9f6-d805fd5d3473)

**Contexte supplémentaire**
Jeedom beta 4.4.6
debian 11.9
php8.3
VM FreeboxDelta

**Comment by pifou25** [comment]
Normalement, si on peut préparer la requête avec un paramètre à condition d'utiliser la notation :number dans le SQL : 
```
     $values = array(
       'number' => $delete_number,
     );
     $sql = 'DELETE FROM timeline ORDER BY `datetime` ASC LIMIT :number';
     DB::Prepare($sql, $values, DB::FETCH_TYPE_ROW);
```
Ainsi, ça devrait remplacer :number par sa valeur...

**Comment by Ultraboss77** [comment]
J'ai déjà tenté de faire comme ça oui, mais justement la valeur du paramètre ressort en type string, ce qui provoque une erreur de syntaxe sql !
Le seul moyen de faire propre, c'est de binder le paramètre.

**Comment by zoic21** [comment]
Bonjour,
Pas sur que le bug vienne de php8 a mon avis il est sur toute les plateforme. Je vais tester un fix
