### ISSUE TITLE
Possibilité d'archiver par parquet en dessous d'une 1h ?

### ISSUE THREAD

**Issue by Loic-Fournier** [jeedom/core#2670]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**
Non

**Décrivez la solution que vous souhaitez**
Serait-il possible de proposer une période d'archivage inférieure à 1h (option "Archiver par paquet de (h)" dans le menu de configuration général Jeedom, puis onglet "Equipements") ?
L'idée étant par exemple de renseigner 0.5 pour pouvoir archiver par 30min.
J'imagine qu'il faudra gérer des valeurs farfelues comme "0.02658h". Peut-être en autorisant des valeurs multiples de 0.5h ?.

**Décrivez les alternatives que vous avez envisagées**
Aucune. J'imagine que gérer un historique recalculé en passant par un bloc code scenario doit être possible, mais pas du tout user-friendly.

**Contexte supplémentaire**
L'idée étant d'améliorer la précision d'un historique archivé. Exemple concret : les historiques archivés liés aux puissances électriques consommées/produites sont trop peu précises par paquet de 1h. A contrario, désactiver le lissage d'archivage rempli la table historyArch à vitesse grand V... D'où l'intérêt de ma requête => trouver un juste milieu.
Merci d'avance pour votre support.

**Comment by zoic21** [comment]
Bonjour,
Dans ce cas je pense qu'il sera plus simple de ne pas demander de l'archivage et de limiter a 1 valeur toute les 10min (je peux voir pour rajouter toute les 30min), c'est une nouvelle option qui arrivera en 4.4.7.

**Comment by Loic-Fournier** [comment]
La solution me conviendrait, mais comment limiter une valeur toutes les 10min ?
Dans mon cas concret, une commande info est "bombardée" par une maj venant d'un device MQTT toutes les 5 à 10 sec. Comment limiter ces données par "paquets de 10min" ? ou bien moyenner par 10min ?
Si besoin, je peux ouvrir un sujet sur community pour ne pas polluer les issues github.
Merci d'avance.

**Comment by zoic21** [comment]
Bonjour,
Comme dit plus haut c'est une fonctionnalité qui arrivera dans la 4.4.7
