### ISSUE TITLE
[BUG] In php8 issue with cronExpression lib does not handle year anymore

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#2698]
https://community.jeedom.com/t/declenchement-programme-unique-plus-si-unique/127301

**Comment by tomitomas** [comment]
@zoic21 pourquoi fermer ?! 
Le problème n est pas résolu 

A moins qu il y ait une 2nd issue créée ?

**Comment by zoic21** [comment]
Le probleme de cette issue est resolu jeedom a repris a son niveau la gestion de l'année dans les expressions cron.

**Comment by tomitomas** [comment]
comme je le précisais au dans mon précédent msg : "le problème n'est pas résolu" 
du moins pas avec les qlq commit de cette issue
ni avec la derniere version alpha

à la sauvegarde pour execution dans 1 min => c'est OK
![image](https://github.com/jeedom/core/assets/12429858/5bf40a1a-2756-460c-9d1c-c0ccdd04dedf)


une fois l'exécution du scénario (ok) faite, un refresh/sauvegarde du scénario, nous indique toujours une "prochain" exécution => +7 jour par rapport au lancement initialement demandé 
![image](https://github.com/jeedom/core/assets/12429858/3e97182c-d9ee-4b4b-a2dd-990d603313f8)

**Comment by zoic21** [comment]
C'est pas le meme soucis la, c'est un autre bug (qui semble plus interne a la lib cron) car l'année est bien respectée (2024).

**Comment by zoic21** [comment]
Edit : trouvé il ne faut pas préciser jour de la semaine en meme temps que la date (je pense jour de la semaine prend le pas sur la date). Pour ton cas il faut mettre `1 10 3 7 * 2024` par exemple

**Comment by tomitomas** [comment]
il faudrait modifier le jeeHelper cron pour mettre cette étoile sur le jour si le choix "une seule fois" est sélectionné
==> fichier `core\desktop\modal\cron.human.insert.php` ligne 71 , remplacer le `date.getDay()` par `'*'`

**Comment by zoic21** [comment]
Effectivement ca par contre c'est un bug, c'est corrigé. Merci pour le retour
