### ISSUE TITLE
[BUG] Traduction Bouton dans la page

### ISSUE THREAD

**Issue by JEALG** [jeedom/core#2722]
**Décrire le bogue**
Il manque la traduction des boutons en anglais dans la page LOG

- Vider Tout
- Supprimer Tout

Pour info Version Core 4.4.9 Alpha

<img width="827" alt="image" src="https://github.com/jeedom/core/assets/48254791/69a2689c-e562-4503-a55f-078006145aac">

**Reproduire**
Etapes pour reproduire le comportement :
1. Avoir la langue en anglais
2. Aller sur 'Analysis/log'
3. Voir la copie d'écran
4. Voir l'erreur

**Comportement attendu
Traduction des 2 boutons

Dans la partie Configuration

- Onglet Général
      - une bonne partie des infos bulles ne sont pas traduite
- Onglet Interface => manque pratiquement toutes les traductions

<img width="2035" alt="Capture d’écran 2024-06-30 à 11 55 08" src="https://github.com/jeedom/core/assets/48254791/fd9dc33c-24d2-4d66-a3f4-aa7ba01ec0ca">

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour, soucis avec le robot de traduction c'est maintenant corrigé.
