### ISSUE TITLE
[BUG] plan.js

### ISSUE THREAD

**Issue by mike59122** [jeedom/core#2788]
Bonjour, 
depuis la mise à jour du core en version 4.4.9 je me retrouve de temps en temps avec une erreur Js sur le fichier plan.js
erreur relevée par jeedom:
Uncaught ReferenceError: jeedomUI is not defined ligne 1356
Merci d'avance

**Comment by zoic21** [comment]
Bonjour,
Il faut plus de details la je peux absolument rien faire.
