### ISSUE TITLE
Amélioration du widget multiligne

### ISSUE THREAD

**Issue by Antoinekl1** [jeedom/core#2876]
Bonjour

serait il possible d'ajouter au widget multiligne :
- une option pour changer la couleur du fond
- une option minHeight
- et si le titre pouvait être placé au dessus de la zone et non à suivre

l'idée serait de pouvoir obtenir ce type de widget :
![image](https://github.com/user-attachments/assets/805f9935-4cc3-4a23-bf4d-1c0966287cf2)

merci

**Comment by zoic21** [comment]
Bonjour,
J'ai ajouté la couleur de fond et le minHeight pour le retour a la ligne c'est pas si simple car si je l'ajoute je vais casser l'affichage chez tout le monde ce qui ne passera pas sur le community et je vais encore me faire incendier.

**Comment by Antoinekl1** [comment]
Bonjour

Merci Loïc

Ça ne peux pas ce gérer par une option pour le titre ?

Crdl

**Comment by Antoinekl1** [comment]
Ok je comprends et faire un multilingue2, ce n'est pas envisageable ?

En fait je ne vois pas dans quel cas on aurait intérêt à avoir le titre devant le texte, ce n'est pas très esthétique mais je me trompe peut être 

Merci pour les motifs

**Comment by zoic21** [comment]
Ca je peux pas te dire quand ca sert, ce que je sais c'est que maintenant je limite  un maximum les changements qui vont toucher l'interface.

**Comment by Antoinekl1** [comment]
Bonjour OK, merci
comme on sait que la modification est disponible, j'ai passé la .15 et la .16 du jour mais je vois pas de modif dans le widget

![image](https://github.com/user-attachments/assets/3951f86c-5d47-4e40-890a-2458876d075d)

**Comment by zoic21** [comment]
La modification est disponible que en PR (pas accepté par jeedom pour le moment) . Pour rappel je prend du temps a détailler les changelog maintenant donc si la modification avait été dispo tu l'aurais eu dans le changelog

**Comment by Antoinekl1** [comment]
Bonjour, ok je lis consciencieuse tes changelog
