### ISSUE TITLE
[BUG] Docker image (5dd82e2d1b08) exit

### ISSUE THREAD

**Issue by fred-gb** [jeedom/core#2880]
Bonjour, 👋🏻 

J'ai voulu démarrer avec l'image `latest`  (sha256:5dd82e2d1b08038d49d7592dfb53e9b0f53a043180213781e7dbe2672ee632fe)

Exit error en boucle avec ce message d'erreur:
```
chmod: changing permissions of '/dev/tty': Operation not permitted
```

Je n'ai pas pris le temps de plus voir les logs pour l'instant car j'ai vu vite remettre en place la prod. J'ai réutilisé l'image (sha256:18176d7bab6de05e6ddd45ffd92803ef9b0a248c5b35b386b64c6f3f988d42e4) et ça fonctionne très bien.

Voilà pour information.

**Comment by zoic21** [comment]
Bonjour,

Je pense qu'il y a un soucis de droit la sur votre docker, il a accès au port TTY mais sans avoir le droit de changer les droits dessus (ce dont jeedom a besoin si vous voulez y accéder).

Dans tous les cas j'ai supprimer cette ligne car les plugins le font aussi.
