### ISSUE TITLE
[BUG] Commandes en double dans "Utilisé par"

### ISSUE THREAD

**Issue by BadWolf42** [jeedom/core#2891]
**Décrire le bug**
Toutes les commandes sont en double dans "Utilisé par":
![image](https://github.com/user-attachments/assets/f0c9bd31-0a74-45b0-bcf8-ac9f34b24e77)

**Reproduire**
Etapes pour reproduire le comportement:
1. Créer une commande source (ici `4609`):
![image](https://github.com/user-attachments/assets/24bd5cdb-0b42-4344-be09-0e6904bc64da)
2. Créer une commande cible (virtual ou autre, ici virtual `12218`) qui référence la commande source:
![image](https://github.com/user-attachments/assets/073538b7-520a-43da-aa4f-9e8958de1563)
3. Dans la "Configuration Avancée" de la commande source, on voit 2x la commande cible:
![image](https://github.com/user-attachments/assets/f0c9bd31-0a74-45b0-bcf8-ac9f34b24e77)
La commande est référencée 2x dans l'autre commande, une fois dans `configuration`, une autre dans `value`:
![image](https://github.com/user-attachments/assets/c0d476a2-13ab-4994-8edd-d0324f6fcd61)

Le fait que la commande soit à la fois dans `configuration` et `value` (historiquement pour les events) est toujours normale/d'actualité ?

Il y a eu un changement dans `cmd::getUsedBy()` entre la 4.3.23 et la 4.4.2:
```
$return['cmd'] = self::searchConfiguration('#' . $this->getId() . '#');
```
https://github.com/jeedom/core/blob/4.3.23/core/class/cmd.class.php#L2670
```
$return['cmd'] = array_merge(self::searchConfiguration('#' . $this->getId() . '#'), cmd::byValue($this->getId()));
```
https://github.com/jeedom/core/blob/4.4.2/core/class/cmd.class.php#L2847
Du coup, `cmd::getUsedBy()` renvoie 2x chaque commande.

**Comportement attendu**
Chaque commande ne doit être présente qu'une seule fois dans "Utilisé par".

**A noter que :**
Si `cmd::getUsedBy()` est utilisée pour propager les évènement, 
Alors il y fort à parier que chaque évènement soit envoyé 2 fois !

Bad

**Comment by zoic21** [comment]
C'est corrigé et c'est normal d'avoir dans value et config, value permet a jeedom de savoir qu'il faut mettre a jour la commande quand la commande de value change.
