### ISSUE TITLE
[BUG] backup download get lost with symlinks

### ISSUE THREAD

**Issue by KipK** [jeedom/core#2895]
**Describe the bug**
When backup folder is a symlink, downloading a jeedom backup fails with wrong path giving "file not found ..."

**To Reproduce**
1. set /var/www/http/backup folder as a symlink to /var/backups/jeedom
 note: on my use case, /var/backups is mounted to an HDD instead of main SDD, that's why i symlink to HDD all services writing to disk on a regular basis  to preserve SDD wearouts.

2. on Jeedom frontend, go to settings / backup , select a backup and click download file
3. This will display blank page with: 
` file not found error /var/www/html//var/backups/jeedom/backup-Jeedom-4.4.16-2024-09-12-18h28.tar.gz`

**Expected behavior**
It should not resolve the symlink path but try to get the file from /var/www/html/backup/backup-Jeedom-4.4.16-2024-09-12-18h28.tar.gz

**Cause**
PHP magic constants `__DIR__ ` and `__FILE__` resolve symlinks automatically:

`be aware that __DIR__ and __FILE__ will return values based on the fpm root which MAY differ from its actual location on the file system.`

**references**
some intels probably related to this issue here: 
https://www.php.net/manual/en/language.constants.predefined.php
https://stackoverflow.com/questions/3221771/how-do-you-get-php-symlinks-and-file-to-work-together-nicely
https://stackoverflow.com/questions/13771021/php-dir-or-file-symlinked

**solution**
I'm no php expert but this library was made to solve this issue :
https://github.com/logical-and/symlink-detective
however, it hasn't been updated for 7 years so probably not safe to use.

Perhaps the simpler way would be to have the backup path directly configurable in Jeedom

**Comment by zoic21** [comment]
Hello,
It's normal, we don't allow symlink.

**Comment by KipK** [comment]
And what about having the backup path configurable ? For now it's hardcoded, so not much solution than using symlinks.

**Comment by KipK** [comment]
> Hello, It's normal, we don't allow symlink.
This seems to be a bit trivial decision as symlink has it's advantage on a devops point of view.

Also, then, why apache config after jeedom install has AllowSymlink enabled by default... if it's assumed, it should then be disabled by default.
