### ISSUE TITLE
[BUG] plan

### ISSUE THREAD

**Issue by mike59122** [jeedom/core#2903]
Bonjour,
je pense qu'il y a un soucis sur les desing,
en effet je me retrouve régulièrement avec l'erreur suivante:

widget.js:325 Uncaught TypeError: Cannot read properties of null (reading 'style')

voici la ligne en question
document.querySelector('.eqLogic[data-eqLogic_uid=' + uid + ']  .Climatisation').style.setProperty('color', 'rgb(52, 152, 219)', 'important');

La classe Climatisation existe bien, cependant le uid  de l'eqLogic change très souvent (+- 4sec)

en cherchant plus loin je me suis aperçu qu'il y a un appel quasi permanant à la fonction getHtml()
en ajoutant cette ligne en ligne 230 sur le fichier plan.class.php:

 log::add("jeedom","debug",json_encode(debug_backtrace()));
voici le retour:
DEBUG  : [{"file":"\/var\/www\/html\/core\/ajax\/plan.ajax.php","line":59,"function":"getHtml","class":"plan","object":{},"type":"->","args":["dashboard"]}]

nous voyons parfaitement un appel permanent à la fonction.
ce problème se produit uniquement sur les desings quelque soit les eqlogics affichés. sur le dashboard ça ne se produit pas.

DEBUG  : [{"file":"\/var\/www\/html\/core\/ajax\/plan.ajax.php","line":59,"function":"getHtml","class":"plan","object":{},"type":"->","args":["dashboard"]}]

cela a pour conséquence de dégrader l'affichage et de continuellement faire des appel ajax inutilement, du coup de faire monter le load average du CPU.

j'utilise jeedom en version 4.4.17 en version stable sur un RPI 3b+ avec debian 10.13 et PHP| 7.3.31

**Comment by zoic21** [comment]
Bonjour,
Nous n'avons aucun widget avec la class climatisation c'est donc un widget custom et non core. Il faut voir avec le dev du widget.
