### ISSUE TITLE
[BUG] [4.5 Alpha] MAJ et pollution du centre de messages

### ISSUE THREAD

**Issue by rroblik** [jeedom/core#2914]
**Décrire le bogue**
Les MAJ de plugins ou du core polluent le centre de messages

**Reproduire**
Etapes pour reproduire le comportement :
1. Allez à `Réglages > Système > Centre de mises à jour`
2. Cliquez sur `Mettre à jour`
3. Choisir `✅ Mettre à jour le Core` et `✅ Mettre à jour les plugins`
4. Valider

**Comportement attendu**
Pas de message particulier dans le centre de message

**Captures d'écran**
![image](https://github.com/user-attachments/assets/e0d5c1ae-41cd-43fa-8d47-3679bc42b53e)

Ce comportement est observé depuis environ 2 semaines je dirais et pour moi il n'est pas souhaitable. L'action de faire les MAJ est manuelles (= action utilisateur) il n'y a pas de raison de ressortir des messages dans le centre de messages, dédié aux messages générés en arrière plan. Par ailleurs l'update (core) a son propre log et c'est (c'était) parfait ainsi.

Merci !

**Comment by zoic21** [comment]
Bonjour,
Le core est il bien a jour ? J'ai corrigé ce bug il y a au moins une semaine....
