### ISSUE TITLE
Améliorer la résilience du backup / restore

### ISSUE THREAD

**Issue by pifou25** [jeedom/core#2921]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**

Cette suggestion suite à une erreur fatale lors de la restauration de mon backup d'un raspberry pi / docker (donc DIY) sur une luna - et en particulier suite à ce bug
https://community.jeedom.com/t/erreur-restore-backup-jeedom-avec-le-plugin-jeemate/131512/5

Il faudrait rentre la restauration résiliente à toute sorte d'erreurs... Et, au pire du pire, si l'opération de restaure n'a pas marché, prévoir un plan B pour revenir à un état fonctionnel, par exemple remettre l'ancien backup ? En l'état, l'import mysql a planté et on se retrouve avec une db parfaitement vierge.

**Décrivez la solution que vous souhaitez**

Il faudrait rentre la restauration résiliente à toute sorte d'erreurs... Et, au pire du pire, si l'opération de restaure n'a pas marché, prévoir un plan B pour revenir à un état fonctionnel, par exemple remettre l'ancien backup ? En l'état, l'import mysql a planté et on se retrouve avec une db parfaitement vierge.

* Avant de lancer la restauration, on devrait s'assurer qu'il y a déjà un autre backup disponible - autre que celui qu'on essaye de restaurer, et surtout un qui corresponde à l'état en cours... en fait, si besoin on pourrait même faire un backup avant de restaurer le nouveau.
* En cas de plantage du restore, on conserve le log d'erreur, mais on restaure l'ancien backup pour revenir à une situation stable.

**Décrivez les alternatives que vous avez envisagées**

Autre possibilité, jouer l'import mysql dans une autre db pour la vérifier... Mais nécessite de créer une 2e db, il faut être root sur mariadb.
Je n'ai pas trouvé de mode "dry-run" pour l'import mysql ça aurait été une solution aussi... 
Pour mon cas particulier, on pourrait exclure les triggers du backup (mais du coup le plugin concerné marchera beaucoup moins bien après restaure...)
MariaDB supporte l'option --force: Continue even if we get an SQL error
https://mariadb.com/kb/en/mariadb-command-line-client/#-f-force

**Contexte supplémentaire

Ajoutez ici tout autre contexte ou capture d'écran concernant la demande de fonctionnalité.

**Comment by zoic21** [comment]
Bonjour,
Oui c'est le reve de tous logiciel au monde avoir un truc qui plante pas... Au dela de la blague le backup ne peut pas etre plus resilient.

De plus la ton soucis : 
- et dans mysql/mariadb rien a voir avec jeedom il faudrait voir avec eux
- du a l'utilisation de trigger dans jeemate il faut voir avec le dev du plugin
