### ISSUE TITLE
Listing des backups esclaves dans Réseau Jeedom

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#297]
Bonjour,

Je pense qu'il y a un petit bug sur la partie Réseau Jeedom.
En effet j'ai 2 esclaves, et quand je suis sur un esclave ou l'autre, dans l'onglet Backup, les backups des 2 esclaves sont mélangés dans le "select"
A priori il ne devrait y avoir en choix que des backups de l'esclave en cours de visualisation

**Comment by zoic21** [comment]
Bonjour,
Non cela est normal ça permet de transférer un esclave vers un autre en cas de remplacement.
