### ISSUE TITLE
[BUG] Erreur PHP sur le dashboard, widget avec statistiques sur commande numérique sans valeur

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#2988]
Jeedom Stable 4.4.19
PHP 8.2
Debian 12.8

Hello,

Après la création d'un nouvel équipement dans le plugin Mqtt Manager (mqtt2), avec des commandes contenant des infos numériques historisées, et avec l'affichage des statistiques sur le widget, en allant sur le dashboard je me suis rendu compte que l'affichage du dashboard était planté à l'endroit du widget concerné.

En regardant les logs PHP j'ai vu ça:
`PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/jeedom/core/class/cmd.class.php:1744`

la ligne de code PHP correspondante:
`$replace['#averageHistoryValue#'] = round($replace['#state#'], 1);`

Après une première remontée des valeurs sur Mqtt, l'erreur a disparu et tout est ok.
Je pense donc que c'était l'affichage des statistiques des commandes numériques qui a provoqué l'erreur car à la création des commandes les valeurs numériques étaient inexistantes.

Merci

**Comment by zoic21** [comment]
Bonjour,
Merci pour le retour c'est corrigé en 4.5 depuis un moment. Donc ca sera bon dans celle ci
