### ISSUE TITLE
Listing des widgets affichage avancé

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#304]
Bonjour,

Suite au post de Loïc sur le blog, je me suis rendu compte du (nouveau ?) widget timePresence qui ne fait à priori pas parti du plugin widget.

Du coup, je me demande si il ne serait pas possible de faire la distinction dans le listing des widgets dans l'affichage avancé, entre les widgets core/intégrés et les widgets du plugin, et là encore détailler dans les widgets du plugin la différence entre les officiels et les tiers.
Le but étant de pouvoir prioritiser l'utilisation des widgets intégrés au core ou officiels, mais une fois qu'on a un gros listing de widgets difficile de faire le tri et de se souvenir de qui est quoi.
Peut etre en mettant un flag [core/officiel] , [plugin/officiel] , [plugin/tiers] , quelque chose du genre, devant les noms des widgets..

Ensuite plus ou moins même demande dans le plugin widget, pouvoir faire la distinction entre les officiels et les tiers, car après l'installation d'un widget on ne dispose pas de cette info dans l'affichage des "tuiles" de widget ni dans le détail d'un widget après ouverture.

Dernier point, mais là c'est du bonus... ça serait que dans le listing des widgets dans affichage avancé, il y ait un preview en image par exemple.

Merci :)

**Comment by zoic21** [comment]
Bonjour,
Pour la distinction entre core/widget c'est déjà fait dans la beta ça sera donc dans la 2.1, vu que tout les widget officiels seront dans le core il n'y a pas besoin de faire une distinction entre plugin/officiel et plugins/tiers.

Pour la preview ce n'est pas si simple et ça peut faire bugué l'interface si il y a un soucis dans le widget donc pour l'instant je n'en mets pas.

**Comment by spyjo** [comment]
Ok super pour les widgets officiels dans le core, je pense que c'est une bonne avancée :) 

Pour ce qui est de la preview, je pensais déjà dans un premier temps au screenshot comme on peut voir dans le plugin widget, pas forcément un rendu en temps réel de la commande en cours de modification même si ça serait encore mieux. Sinon peut être faire un preview en iframe pour ne pas faire buguer l'interface en cas de soucis sur le widget

**Comment by zoic21** [comment]
Le soucis de l'image c'est que ca rend pas toujours bien et ca multiplie le boulot à chaque mise à jour.

Pour les iframe c'est déjà ce que je fais sur le plugin widget et j'ai quand même des soucis du a la div de chargement.
