### ISSUE TITLE
Scenario avec module Santé

### ISSUE THREAD

**Issue by rd2b** [jeedom/core#305]
Bonjour,

Ca serait sympa de pouvoir utiliser le module santé de Jeedom dans les scenarios,

On pourrait déclencher des actions en cas d'insidponibilité d'un des composants et envoyer des informations particulières.

Merci

**Comment by zoic21** [comment]
Bonjour,
Ce n'est malheureusement pas possible car il n'y a pas de verification sur la page santé c'est vérifie à la demande.

**Comment by rd2b** [comment]
Et une cron qui regénère une fois/jour ?

Ca permettrait de disposer des valeurs quelque part
