### ISSUE TITLE
Intéractions phrases à disallow

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#309]
Bonjour,

Après avoir appliqué le filtre des phrases dans les intéractions, ça m'a presque viré toutes les incohérences donc parfait ;)
de mon coté il ne me reste plus que ces mots là qui restent incohérents:

le maison
du maison
le buanderie
du buanderie
la bureau
la systeme

Loic si tu peux les ajouter à la liste des "disallow" stp :) merci

**Comment by zoic21** [comment]
C'est ajouté sauf pour "la systeme" qui est trop générique (mais tu peux le rajouter manuellement). Ca sera par contre dispo que en jeedom 2.2 je pense.

**Comment by spyjo** [comment]
ok merci ;)
