### ISSUE TITLE
Bug sur la page "tester les intéractions" + conversion binaire dans chiffre

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#310]
Bonjour,

Un léger bug sur le formulaire de test des interactions, quand on fait "entrer" au lieu de cliquer sur Exécuter, ça nous envoie sur le dashboard.

Autre bug (?), pour une interaction de type "Réponse: #valeur# #unite#", sur tout type d'info
si je demande "quelle est la température du salon", il me répond:
Réponse: 2faux.7 °C
on dirait qu'il remplace le "0" par "faux" à cause de ma configuration "conversion binaire".
par contre cette option ne devrait-elle pas s'appliquer uniquement quand la valeur envoyée est justement de type binaire et pas numérique ou autre ?

merci

**Comment by zoic21** [comment]
Bonjour,
1) c'est déja corrigé en 2.1
2) oui c'est connu il faut séparer en 2 interactions les binaires et les autres

**Comment by spyjo** [comment]
ok j'y pensais justement à séparer en 2 les réponses binaires et autre, mais je m'étais dit au cas ou que lors du traitement de la réponse tu avais le sous-type de la valeur de dispo pour savoir si tu dois remplacer ou pas le mot binaire

**Comment by zoic21** [comment]
Non je le perd lors du replace malheureusement.
