### ISSUE TITLE
Chemins relatifs de l'écran setup.php incorrects

### ISSUE THREAD

**Issue by tpoisson** [jeedom/core#314]
Bonjour,

J'ai remarqué que les chemins relatifs des ressources JS/CSS/images du fichier setup.php sont erronés.
Cela fonctionne en accès direct (http://IP:PORT/), mais avec de l'URL rewriting avec un contexte (/jeedom/ par exemple), les ressources ne se chargent pas.

Exemple concret : 
../../3rdparty/jquery/jquery.min.js

à ré-écrire en : 
../3rdparty/jquery/jquery.min.js

Thomas

**Comment by zoic21** [comment]
Effectivement, merci pour le retour j'ai corrigé en beta ca sera dans la prochaine stable.
