### ISSUE TITLE
Restauration de plugins avec résolution des dépendances simultanées

### ISSUE THREAD

**Issue by tpoisson** [jeedom/core#315]
Je m'amuse un peu avec la sauvegarde/restauration de Jeedom et je constate que la restauration des plugins qui contiennent des dépendances se fait de manière simultanée.
Exemple des plugins "Network" et "Zwave", la résolution se fait en même temps, c'est le premier qui obtient le "lock" qui gagne, laissant l'autre planter.

Thomas

**Comment by zoic21** [comment]
Bonjour,
C'est un soucis connu que nous ne savons pas comment résoudre du au lancement en background.
