### ISSUE TITLE
Jeedom n'est pas démarré

### ISSUE THREAD

**Issue by tpoisson** [jeedom/core#316]
J'ai un souci avec une "fresh install" (dans un Docker, ça joue?)
La fonction :

public static function isStarted() {
        return file_exists('/tmp/jeedom_start');
}

retourne toujours false, car le fichier n'est pas présent (je ne sais pas à quelle étape il est créé).
Le démon OpenZwave ne veut pas démarrer car il se base sur cette info pour se lancer ou pas.
J'ai créé le fichier à la main pour résoudre le problème.

**Comment by zoic21** [comment]
C'est les crons qui normalement font ça lors du lancement la première fois de ceux-ci. Après le docker est loin d'être prêt il est plus au stade alpha que autre chose.
