### ISSUE TITLE
Ajout d'une icone indiquant si le démon est démarré en debug ou non

### ISSUE THREAD

**Issue by zoic21** [jeedom/core#319]

**Comment by pipersw** [comment]
est-ce en rapport avec [https://www.jeedom.com/forum/viewtopic.php?f=58&t=16432](url) ?
Je ne vois pas de différences sur l'icone de debug.
Faut-il faire quelquechose d'autre ?

**Comment by zoic21** [comment]
Bonjour,
Oui par contre pour l'avoir il faut attendre que ça soit disponible en stable actuellement ça n'est visible que sur la beta

**Comment by pipersw** [comment]
ok, pas de soucis, et encore bravo pour tout ce travail sur Jeedom.

**Comment by pipersw** [comment]
ok, pas de soucis, merci beaucoup pour ton travail
