### ISSUE TITLE
Suggestion widget core + décalage widget tile

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#321]
Bonjour,

Par rapport aux widgets core, avec notamment le timePresence, je me demandais si il ne serait pas intéressant d'avoir la même variante avec le temps affiché en dessous pour les widgets door et window.

Autre chose, depuis le passage v2 d'il y a qq semaines, j'ai un petit décalage des chiffres avec le widget "tile (core)" que je n'avais pas en v1:
<img width="336" alt="capture d ecran 2016-03-08 a 01 12 31" src="https://cloud.githubusercontent.com/assets/4271747/13587805/f52693be-e4ca-11e5-8040-613c7450c3ae.png">
Je me demandais si ça ne le fait que chez moi ou si c'est général. (c'est un virtuel avec 3 infos numériques)

Merci

**Comment by zoic21** [comment]
Bonjour,
Je viens d'ajouter les widgets time pour door et windows (ca sera disponible en 2.2.1).

Pour le décalage il est volontaire c'est un effet que j'aime bien.

**Comment by spyjo** [comment]
Ok merci ;)
