### ISSUE TITLE
Problème de vitesse d'exécution des scénarios 

### ISSUE THREAD

**Issue by geraldgg** [jeedom/core#330]
Plusieurs sujets en parlent sur le forum :
https://www.jeedom.com/forum/viewtopic.php?f=23&t=17128&p=308350#p308350

https://www.jeedom.com/forum/viewtopic.php?f=23&t=17128&start=20

J'y décris le problème, qui vient de l'écriture dans la bdd. 
Il faudrait plus de log en debug pour y voir plus clair, mais ça semble correspondre aux symptômes des autres utilisateurs.

**Comment by zoic21** [comment]
Bonjour,
Je pense que ca vient de l'ajout de cette vérification : https://github.com/jeedom/core/blob/beta/core/class/scenario.class.php#L1155, il n'y a pas de solution pour le moment.
