### ISSUE TITLE
Petit bug titre popup caméra + visibilité Rafraichir

### ISSUE THREAD

**Issue by spyjo** [jeedom/core#343]
Bonjour,

En 2.2.6, j'ai un tout petit bug sur la page des caméras ( /jeedom/index.php?v=d&m=camera&p=panel )
En cliquant sur une des caméras, le titre de la popup qui s'ouvre est "#humanname#"

Autre petit bug, pour la visibilité du bouton Rafraichir, si on passe le réglage "Visible" dans l'onglet "Informations" à non, cela ne fonctionne pas. Par contre si on mets Visible à non dans "Affichage avancé" par type d'affichage, là c'est ok. Donc c'est juste le réglage global à la commande qui ne prend pas le dessus sur les réglages fins.

Merci :)

**Comment by zoic21** [comment]
Bonjour,
J'ai poussé la correction pour le plugin camera (attention par contre la c'est le git du core pas du plugin caméra).
Et j'ai fait la correction ce matin déjà pour le soucis de visibilité sur la commande rafraîchir (ca sera donc dans la prochaine stable)

**Comment by spyjo** [comment]
Ok merci :)

Pour le git, je n'ai pas accès au git camera, d'où mon post ici ;)
