### ISSUE TITLE
systemd is missing on Bananian or Raspbian for Banana

### ISSUE THREAD

**Issue by pipersw** [jeedom/core#37]
Sur Raspbian pour Raspberry, le package systemd est présent, et il n'y a pas de probleme d'instalaltion.

Sur Raspbian pour Banana Pi et sur Bananian, ce package est absent de base, il faut le rajouter pour ne pas avoir d'erreur sur systemctl :

echo "********************************************************"
echo "${msg_setup_nodejs_service}"
echo "********************************************************"
cp install/jeedom /etc/init.d/
chmod +x /etc/init.d/jeedom
update-rc.d jeedom defaults

__apt-get install -y systemd__

if [ -d /etc/systemd/system ]; then
	cp install/jeedom.service /etc/systemd/system
	systemctl enable jeedom
fi

**Comment by zoic21** [comment]
C'est ajouté, merci

**Comment by orx57** [comment]
`systemd` est disponible dans Debian Wheezy en _preview_ technologique.
Il n'est pas conseillé d'utiliser `systemd` sur une Debian Wheezy (stable) basé aujourd'hui sur **SysVinit**.

L'installation de `systemd` a pour effet de supprimer les packages suivants : 

- fake-hwclock
- init-system-helpers

L'absence de `fake-hwclock` peut être à l'origine de problème d'horloge au redémarrage du Raspberry Pi (ou similaire).

Debian Jessie (actuellement testing) sera basé sur `systemd`.

Je suggère de n'utiliser que le script `/etc/init.d/jeedom` en attendant une Debian nativement basée sur `systemd` pour éviter tout conflit possible.
