### ISSUE TITLE
Update Z-wave firmware nodes

### ISSUE THREAD

**Issue by jcastro** [jeedom/core#375]
Hello!

I would like to test jeedom on my raspberry pi2. I currently have an Aeotec Z-stick Gen5, and among other devices, I have an Aeotec Multisensor 6 that I know it has a firmware update available. Would it be possible from jeedom to update this z-wave node? I know Gen5 supports this but not sure if the software does!

Thanks a lot!

**Comment by nechry** [comment]
Hi @jcastro The plugin zwave and the lib openzwave do not support the OTA feature. 

please check: https://aeotec.freshdesk.com/support/solutions/articles/6000036562-how-do-i-upgrade-the-firmware-for-multisensor-6-

but a update 1.07 are just released but not yet referenced.
