### ISSUE TITLE
Mise à jour de composer.json

### ISSUE THREAD

**Issue by kwizer15** [jeedom/core#380]
J'ai besoin d'ajouter une dépendence via composer pour avoir des tests plus propore sur le système de fichier. En faisant un `composer require`, ca m'a viré quelques trucs et fait des régressions dans les versions.

```
  - Removing knplabs/github-api (1.6.0)
  - Removing guzzle/guzzle (v3.9.3)
  - Removing symfony/event-dispatcher (v2.8.4)
  - Removing illuminate/support (v5.2.28)
  - Removing illuminate/contracts (v5.2.28)
  - Removing paragonie/random_compat (v1.4.1)
  - Removing christian-riesen/base32 (1.3.0)
  - Removing simplesoftwareio/simple-qrcode (1.3.3)
  - Removing pragmarx/google2fa (v0.7.1)
  - Removing bacon/bacon-qr-code (1.0.1)
  - Removing doctrine/inflector (v1.1.0)
  - Removing mtdowling/cron-expression (v1.1.0)
  - Installing mtdowling/cron-expression (v1.0.4)
    Downloading: 100%         

  - Removing symfony/expression-language (v2.8.4)
  - Installing symfony/expression-language (v2.6.3)
    Downloading: 100%         

  - Removing league/oauth2-client (1.3.0)
  - Installing league/oauth2-client (1.4.1)
    Downloading: 100%         

  - Installing mikey179/vfsstream (v1.6.3)
    Downloading: 100%         

```
Le dernier c'est ce que j'ai voulu installé.

**Comment by zoic21** [comment]
Bonjour,
Je viens de tester chez moi pas de soucis (je vais pousser la mise à jour). Par contre je vois pas le but exact.

**Comment by kwizer15** [comment]
Ok merci.
Ca permet de faire un systeme de fichier virtuel. Y a pas mal de de creation de fichiers temporaire etc... dans jeedom. Plutot que de creer et effacer des fichiers "reels" durant les tests, on passe par ca. Je propose, tu disposes.
