### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jeromevdl** [jeedom/core#384]
Bonjour,

Ce n'est pas à proprement parler une issue mais plus des questions.

Pourquoi avoir choisi JsonRPC plutôt que du simple REST (json/http) ?
Je vois ici et là parler d'applications mobiles, qu'en est-il ? Parce qu'il y a la version web mobile mais une app native serait bienvenue...

Merci

**Comment by zoic21** [comment]
Bonjour,
Pas de raison particulière juste je connaissais pas le rest a l'époque donc je suis partie sur le jsonrpc.

Pour l'app mobile il y a l'avancement sur le forum.
