### ISSUE TITLE
History & Php7/mysql5.7.12

### ISSUE THREAD

**Issue by cedric222** [jeedom/core#385]
Bonjour,

Depuis mon passage en php7 (unbuntu 16.4) j'ai ce message d'erreur toutes les nuits. Normal ?

Erreur sur history::archive() : Exception Object
(
[message:protected] => [MySQL] Error code : 22007 (1292). Truncated incorrect time value: &apos;839:00:00&apos;
[string:Exception:private] => 
[code:protected] => 0
[file:protected] => /var/www/html/core/class/DB.class.php
[line:protected] => 101
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /var/www/html/core/class/history.class.php
[line] => 182
[function] => Prepare
[class] => DB
[type] => ::
[args] => Array
(
[0] => DELETE FROM history
WHERE TIMEDIFF(`datetime`,:oldest) Array
(
[cmd_id] => 70
[oldest] => 2016-02-16 22:00:00
[archivePackage] => 01:00:00
)

[2] => 0
)

)

[1] => Array
(
[file] => /var/www/html/core/php/jeeCron.php
[line] => 67
[function] => archive
[class] => history
[type] => ::
[args] => Array
(
)

)

)

[previous:Exception:private] => 
)

**Comment by zoic21** [comment]
Bonjour,
Est ce bien avec mysql ? Je sais qu'il y a des soucis avec mariadb. Il faudrait aussi regarder qu'il n'y a pas un mauvaise enregistrement en base car la comme ca tout est bon pour moi

**Comment by cedric222** [comment]
oui, c'est bien mysql Server version: 5.7.12-0ubuntu1 (Ubuntu)
J'ai pas fait attention que ubuntu avait aussi upgrader mysql

Cette commande à pourtant l'air de fonctionner

select count(*) from history where TIMEDIFF(datetime,'2016-02-16 22:00:00') ;

**Comment by cedric222** [comment]
Je viens de voir que j'ai le meme genre de problème avec calendar

Erreur sur la fonction cronHourly du plugin : [MySQL] Error code : 22007 (1292). Incorrect datetime value: &apos;0000-00-00 00:00:00&apos; for column &apos;until&apos; at row 1

**Comment by zoic21** [comment]
A c'est mysql 5.7 effectivement on a de nombreux soucis avec php 7 et mysql 7 pour résumer jeedom ne marche quasiment pas avec cette architecture. On corrige petit a petit mais c'est loin d'etre notre priorité.

**Comment by dough29** [comment]
Je confirme, j'avais tenté l'aventure MySQL 5.7 et je suis vite revenu en arrière.

**Comment by cedric222** [comment]
re-install en Debian 3.16.7, restaure de jeedom, et cela refonctionne
