### ISSUE TITLE
Make it run in Docker

### ISSUE THREAD

**Issue by arthurlutz** [jeedom/core#95]
Am trying out jeedom in Docker. Some of it seems to be running correctly, but I haven't found a way (yet) to get cron to run. 

A Docker file (and maybe a Docker image) would be a nice way for people to try out jeedom (or to host it on an existing server).

**Comment by zoic21** [comment]
Hi,
It's already exist : http://doc.jeedom.fr/fr_FR/doc-installation.html#docker (sorry it's in french) but docker name is : cquad/jeedom

**Comment by arthurlutz** [comment]
@zoic21 great news. Thanks for the link. 

I'm not a big fan of pull ready made images from docker (cf https://securityblog.redhat.com/2014/12/18/before-you-initiate-a-docker-pull/), so do you think you could publish the Dockerfile if there is one so I (and others) can build it from scratch ? 

Thanks. (and I'm french speaking so no worries)
