### ISSUE TITLE
mise à jour dans un docker : /sbin/ifconfig: not found

### ISSUE THREAD

**Issue by arthurlutz** [jeedom/core#99]
C'est de l'ordre du warning (la mise à jour à bien marché) mais ça pourrais probablement ne pas s'afficher : 

```
****Installation/Mise à jour de Jeedom 1.175.0 (2015-04-09 11:39:58)****
Paramètres de la mise à jour : level : 0, mode : , system : no 
Vérification des mises à jour...sh: 1: /sbin/ifconfig: not found
sh: 1: /sbin/ifconfig: not found
sh: 1: /sbin/ifconfig: not found
sh: 1: /sbin/ifconfig: not found
OK
```

utiliser la command ip à la place ?

**Comment by zoic21** [comment]
Je sais pas si la commande ip est toujours disponible...

**Comment by orx57** [comment]
`ifconfig` fait parti du package _net-tools_.
`ip` fait parti du package _iproute_.

Le package *net-tools* et donc `ifconfig` sont _deprecated_ dans toutes les distributions GNU/Linux (et plu développé depuis 2001). Il vaut donc mieux utiliser `ip`.

**Comment by zoic21** [comment]
Ok j'ai fait le changement dans la derniere beta de jeedom
